langauge: c

script:
  - mkdir build
  - cd build
  - cmake .. -DMPI=OFF -DCMAKE_C_FLAGS="-coverage"
  - make
  - make check
#  - codecov --required


after_success:
  - bash <(curl -s https://codecov.io/bash)
